### ISSUE TITLE
Could TaxonomyTerm add_extension by config.yml ?

### ISSUE THREAD

**Issue by ghost** [silverstripe/silverstripe-taxonomy#24]
Hi!

Could TaxonomyTerm add extension by config.yml? Like this:

TaxonomyTerm:
  extensions:
    - TaxonomyTermExtension

In my page : 
 public static $many_many = [
        'Terms' => 'TaxonomyTerm'
    ];
In the extension
private static $belongs_many_many = [
      'Pages' => 'Page'
    ];

Then I have tried  dev/build but failed. couldn't be worked as 
TaxonomyTerm::add_extension('TaxonomyTermExtension');

I wonder if we could do this by config.yml. Thanks in advance!

**Comment by dhensby** [comment]
What was the error? You should be able to do that in yml

**Comment by robbieaverill** [comment]
@dhensby this user has deleted their account, and the examples seem like a pretty normal use of SS extensions - suggest we close the issue

**Comment by robbieaverill** [comment]
@ghost this looks like standard practice. Please ensure you've flushed (`?flush=1` in the browser) to pick up YAML configuration changes. Feel free to reopen if you're still having issues with this.
