### ISSUE TITLE
Term description

### ISSUE THREAD

**Issue by robingorry** [silverstripe/silverstripe-taxonomy#31]
Hi, 
Do you have an example of how to add another field to the terms, in my cast I'm trying to add a description field to the child term but I just can't get it to work.

**Comment by robbieaverill** [comment]
Hi @robingorry! You can add this with a DataExtension class which is applied to TaxonomyTerm. If you only want it to show up in the CMS for child terms you can use a condition like `if (!$this->Parent()->ID) { // remove new field }` to remove the automatically scaffolded field in these situations. Please feel free to comment if you have any more questions!

**Comment by robingorry** [comment]
Thanks Robbie, got it working strait away.
