### ISSUE TITLE
Check and update module for SS4 compatibility where necessary

### ISSUE THREAD

**Issue by rupachup** [silverstripe/silverstripe-taxonomy#39]
## Acceptance Criteria

- [x] Works on SS4 (pull request #41)
- [x] Update translations (pull request #43)
- [x] Beta tag released

**Comment by raissanorth** [comment]
I noticed while testing that the icon is the wrong colour, but it's probably not blocking a beta release. I've logged it as #42

**Comment by robbieaverill** [comment]
https://github.com/silverstripe/silverstripe-taxonomy/releases/tag/2.0.0-beta1
