### ISSUE TITLE
Feature: Global taxonomy view

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/silverstripe-taxonomy#4]
As a user I can view a page which shows an aggregated list of all content throughout an entire website when I click on a taxonomy term so that I can find related content.

**Comment by camfindlay** [comment]
I think this is actually the same thing as #44 :trollface:

**Comment by NightJar** [comment]
It seems to describe the functionality in the docs, and that #40 has introduced, and #44 aims to improve, yes. To this end, is it OK if I close this issue as superseded by the others?
