### ISSUE TITLE
Term filtering by URLSegment

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/silverstripe-taxonomy#44]
Following on from #40 (once merged) I'd like to add a change to the way the ID parameter string is passed during the request. If it's $Name as is current, TaxonomyTerm with spaces or punctuation would end up getting passed in as the ID. I'd rather this was a URLSegement type slug generated off the $Name. a) it's tidier and b) it follows the rest of SilverStripe URL structure better. 

I'll roll a PR as soon as #40 is merged @dhensby anything blocking that merge?

**Comment by dhensby** [comment]
#40 is merged now

**Comment by camfindlay** [comment]
@robbieaverill bug? enhancement?

**Comment by robbieaverill** [comment]
Skim read - sounded like a bug, but yeah - it's probably an enhancement =)

**Comment by GuySartorelli** [comment]
I don't think this is something we want anymore. I'm going to close the issue, but if someone feels strongly that this should be implemented, has a valid use case for it, and is willing to create a new PR against the correct branch, please say so and I'll reopen the issue at that stage.
