### ISSUE TITLE
Error when adding (non-existent) base page to taxonomy term

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-taxonomy#53]
When selecting a specific taxonomy term in the CMS, opening the Pages tab, and clicking on the ‘Add Base Page’ button (I do not have any pages of type BasePage, but my generic Page extends it), ...

1. I get an internal server error. 
2. The 'Add Base Page' button is decorated with the primary action green. 
3. When I then try to refresh the page the following error pops up:

![image](https://user-images.githubusercontent.com/14869519/38226552-6281145c-374e-11e8-85f9-190b89c95d5c.png)

I am using:
```
silverstripe/framework                    4.1.x-dev 9ed3cd4  
silverstripe/admin                        1.1.x-dev 4166209  
```

**Comment by robbieaverill** [comment]
We should remove the "Add Base Page" action from this gridfield

**Comment by raissanorth** [comment]
I think that is a great idea.

**Comment by NightJar** [comment]
Fixed in https://github.com/silverstripe/cwp/pull/71
