### ISSUE TITLE
v2: Allow developers to disable Type inheritance

### ISSUE THREAD

**Issue by chrispenny** [silverstripe/silverstripe-taxonomy#73]
## Problem statement

At the moment there is an assumption that all Taxonomy hierarchy should share the same `Type`. Any time you attempt to grab the `Type` of a child Term, you will instead get whatever the `Type` of the parent is.

I think this use case has merit, but is not the only use case. We need the ability to have different `Type` assignments for child Terms.

One example where I would like different `Type` assignments is for country/city hierarchies. EG:

* New Zealand (`Type: Country`)
  * North Island (`Type: Region`)
    * Auckland (`Type: City`)
    * etc
  * South Island (`Type: Region`)
    * Queenstown (`Type: City`)
    * etc
* Australia (`Type: Country`)
  * Victoria (`Type: Region`)
    * Melbourne (`Type: City`)
    * etc
  * etc

## Proposal

Add a configuration layer that will allow developers to disable the inheritance of `Type` between parent/child Terms.

PR incoming

**Comment by chrispenny** [comment]
Bump?... PR has been raised. It's hopefully pretty straight forward.

**Comment by emteknetnz** [comment]
Have merged the linked PR
